-- =====================================================================
-- SEED 0300 — Phase 3 (buyers, documents, invoices)
-- =====================================================================
-- Run AFTER 0100_seed_dev.sql and 0200_seed_phase2.sql. Idempotent, fixed
-- UUIDs, safe to re-run.
--
-- What this file does and does NOT do:
--
--   DOES seed supplier↔buyer relationships with fixed ids, so Agent B's
--   buyer search has deterministic content on a fresh database and the
--   wizard's step 1 can be exercised without first driving a resolve.
--
--   DOES NOT seed transactions, invoices, or documents. Those are created
--   by the API, and a hand-written invoice row would be a fiction: the
--   fingerprint, the OCR extraction rows, and the stored object in Supabase
--   Storage are all produced by code paths that must actually run for the
--   row to mean anything. A seeded invoice with an invented fingerprint
--   would make the duplicate check appear to work against data that never
--   went through it — which is the failure mode the Phase 2 audit found in
--   the reverse direction, where residue from live runs was described as
--   seeded fixtures.
--
--   The e-invoice PDFs themselves ARE the Phase 3 seed, and they live in
--   db/seed/einvoices/, generated byte-stably by
--   services/ml/tools/generate_einvoices.py. See docs/specs/EINVOICE_QR.md §7.
--
-- Identity ids are copied verbatim from 0100_seed_dev.sql. Copied, never
-- invented — the lesson both the Phase 1 and Phase 2 audits recorded.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Supplier ↔ buyer relationships (ZM-BUY-008: contact lives HERE, never
-- on the global buyers row).
-- ---------------------------------------------------------------------
-- Contact phone numbers are deliberately absent. The column is
-- `contact_phone_enc bytea` under pgp_sym_encrypt with the runtime
-- ENCRYPTION_KEY, and a seed cannot know that key — writing plaintext into
-- a column every reader expects to be ciphertext would break decryption for
-- the whole table. The API populates it on resolve; these rows exist so the
-- search screen has content, and carry only the fields a seed can honestly
-- supply.

INSERT INTO supplier_buyer_relationships
  (id, supplier_org_id, buyer_id, contact_name, contact_role, contact_email,
   contact_state, relationship_start_date, previous_transactions_count,
   usual_payment_period_days, provided_by_user_id)
SELECT v.id, v.supplier_org_id, b.id, v.contact_name, v.contact_role, v.contact_email,
       'SUPPLIER_PROVIDED', v.start_date, v.prev_count, v.payment_days, v.provided_by
FROM (VALUES
  -- S1 Al-Noor → B1 Amman Retail Group. The demo's protagonist pairing
  -- (Master Plan 6.2) and the happy-path invoice in the seeded set.
  ('0e300000-0000-4000-8000-000000000001'::uuid,
   '0e000000-0000-4000-8000-000000000002'::uuid, '30000201',
   'Nour Salti', 'Accounts payable', 'ap@ammanretail.example',
   DATE '2024-02-01', 14, 90,
   '0e100000-0000-4000-8000-000000000001'::uuid),

  -- S1 Al-Noor → B2 Levant Construction. Second buyer, and the counterparty
  -- on the deliberate OCR-vs-QR mismatch invoice.
  ('0e300000-0000-4000-8000-000000000002'::uuid,
   '0e000000-0000-4000-8000-000000000002'::uuid, '30000202',
   'Rami Odeh', 'Procurement manager', 'procurement@levantco.example',
   DATE '2025-01-15', 6, 120,
   '0e100000-0000-4000-8000-000000000001'::uuid),

  -- S1 Al-Noor → B3 Aqaba Logistics. First half of the duplicate pair.
  ('0e300000-0000-4000-8000-000000000003'::uuid,
   '0e000000-0000-4000-8000-000000000002'::uuid, '30000203',
   'Hala Mansour', 'Finance officer', 'finance@aqabalog.example',
   DATE '2025-06-10', 3, 60,
   '0e100000-0000-4000-8000-000000000001'::uuid),

  -- S2 Petra → B3 Aqaba Logistics. The SAME buyer as the row above, held by
  -- a different supplier with a DIFFERENT contact — which is the whole
  -- reason ZM-BUY-005/008 puts contact data on the relationship. It is also
  -- the second half of the duplicate pair.
  ('0e300000-0000-4000-8000-000000000004'::uuid,
   '0e000000-0000-4000-8000-000000000003'::uuid, '30000203',
   'Ziad Haddad', 'Accountant', 'accounts@aqabalog.example',
   DATE '2025-09-01', 1, 60,
   '0e100000-0000-4000-8000-000000000003'::uuid),

  -- S2 Petra → B1 Amman Retail. Gives Petra a buyer of its own so the
  -- cross-supplier RLS assertions have rows on both sides.
  ('0e300000-0000-4000-8000-000000000005'::uuid,
   '0e000000-0000-4000-8000-000000000003'::uuid, '30000201',
   'Ziad Haddad', 'Accountant', 'accounts@ammanretail.example',
   DATE '2025-03-20', 2, 90,
   '0e100000-0000-4000-8000-000000000003'::uuid)
) AS v(id, supplier_org_id, establishment_no, contact_name, contact_role,
       contact_email, start_date, prev_count, payment_days, provided_by)
JOIN buyers b ON b.national_establishment_no = v.establishment_no
ON CONFLICT (supplier_org_id, buyer_id) DO UPDATE SET
  contact_name  = EXCLUDED.contact_name,
  contact_role  = EXCLUDED.contact_role,
  contact_email = EXCLUDED.contact_email,
  updated_at    = now();

COMMIT;

-- =====================================================================
-- Verification
-- =====================================================================
-- Expect 5 relationships across 2 suppliers and 3 buyers:
--
--   SELECT o.legal_name AS supplier, b.legal_company_name AS buyer,
--          r.contact_name, r.contact_state
--     FROM supplier_buyer_relationships r
--     JOIN organizations o ON o.id = r.supplier_org_id
--     JOIN buyers b        ON b.id = r.buyer_id
--    ORDER BY supplier, buyer;
--
-- Note that Aqaba Logistics appears twice with different contacts. That is
-- the point, not a duplicate.
-- =====================================================================
